### ISSUE TITLE
[Bug] Search For Game doesn't appear

### ISSUE THREAD

**Issue by Jmcmichael97** [moshemartinez/team-1.21GB-project#104]
1. Home Page. 
2. Type "Elden Ring" in search bar with no other input
3. No results 
![image](https://user-images.githubusercontent.com/59668292/234961590-44a61f2d-d0ca-41fb-a4c2-ee9ca7a6e3e2.png)
4. A image of Elden Ring's cover and IGN's rating. 
5. Elden Ring is the top game on your top 100, but doesn't appear in the search. I imagine it's  just a simple DB fix.

**Comment by moshemartinez** [comment]
This issue was due to our IGDB API key being expired.
